controller_manager_ns: controller_manager
controller_list:
  - name: cobotta/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
     - joint_1
     - joint_2
     - joint_3
     - joint_4
     - joint_5
     - joint_6

  - name: cobotta/gripper_ntlab/r_hand_rod_a_position_controller
    action_ns: r_hand_rod_a_joint_position
    type: JointPositionController
    default: true
    joint: r_hand_rod_a

  - name: cobotta/gripper_ntlab/r_base_hand_r_position_controller
    action_ns: r_base_hand_r_joint_position
    type: JointPositionController
    default: true
    joint: r_base_hand_r

  - name: cobotta/gripper_ntlab/l_base_hand_r_position_controller
    action_ns: l_base_hand_r_joint_position
    type: JointPositionController
    default: true
    joint: l_base_hand_r

  - name: cobotta/gripper_ntlab/l_hand_rod_a_position_controller
    action_ns: l_hand_rod_a_joint_position
    type: JointPositionController
    default: true
    joint: l_hand_rod_a

  - name: cobotta/gripper_ntlab/l_finger_roll_position_controller
    action_ns: l_finger_roll_joint_position
    type: JointPositionController
    default: true
    joint: l_finger_roll
